### ISSUE TITLE
Is installation (for mobile) possible?

### ISSUE THREAD

**Issue by Beaidntmeetacoolname** [Feuerhamster/wattpad-downloader#14]
Hi, thanks for the public instance until now, and for keeping the code open, it's very kind of you. I would like to ask if it is possible to us users enable this software as a bot, or app, or any platform that runs on mobile. And if it is possible to do this in a mobile, with some code emulator. Thanks for the reply.

**Comment by Feuerhamster** [comment]
Please read our readme.md file on the start page of this repo.
Everything you need to know is written down there.
