### ISSUE TITLE
How to run wattpad downloader at localhost browser

### ISSUE THREAD

**Issue by jazro247** [Feuerhamster/wattpad-downloader#18]
Hey Friend: 

I have already executed the commands "npm install" and "npm start", but I want to know how to open it locally in the browser to test that it downloads some story from wattpad.

This is what it shows me when I run the commands:

C:\Users\Unknown\Downloads\wattpad-downloader-master>npm install

up to date, audited 199 packages in 9s

16 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

C:\Users\Unknown\Downloads\wattpad-downloader-master>npm start

> wattpad-downloader@1.2.1 start
> node main.js

App started on 2200

**Comment by Feuerhamster** [comment]
The console says
> App started on 2200

So you go on `http://localhost:2200`

**Comment by jazro247** [comment]
it works, so thank you so much my friend
