### ISSUE TITLE
Book limit?

### ISSUE THREAD

**Issue by Eevee125** [Feuerhamster/wattpad-downloader#20]
How would I configure how many books per day you can download?

**Comment by Feuerhamster** [comment]
With environment variables.

These specifically:
```env
# Rate limiter configuration (duration in seconds)
RATE_LIMIT_POINTS = 5
RATE_LIMIT_DURATION = 86400
```

Please see: https://github.com/Feuerhamster/wattpad-downloader#environment-variables

**Comment by Eevee125** [comment]
Ok, thanks

**Comment by Eevee125** [comment]
https://user-images.githubusercontent.com/93407934/146078530-7b729ba3-0897-4b29-b0c4-610330aeb46b.PNG

Is this where the .env file should be?

**Comment by Feuerhamster** [comment]
Yes, but the file should only be named `.env` without the .txt at the end

**Comment by Eevee125** [comment]
Thanks lol I missed that
