### ISSUE TITLE
Estou precisando de ajuda para instalar

### ISSUE THREAD

**Issue by surnoliver** [Feuerhamster/wattpad-downloader#22]
Olá, eu já tentei fazer de tudo, mas nunca mexi com isso tentando aprender para conseguir usar, vocês podem me direcionar de um modo para pessoas mais leigas?

**Comment by Raid4152** [comment]
Estoy igual

**Comment by Alinesete** [comment]
A primeira coisa é ter instalado o Node Js. Se ainda não tiver instalado, só ir no site oficial https://nodejs.org/en/

Depois que instalou certinho, você baixa o wattpad-downloader e extrai em algum lugar.

Quando extrair tudo, você abre a CMD do computador (Tu pode apertar no teclado a tecla Windows + R e escrever cmd ou apertar com o botão direito do mouse no símbolo do Windows do menu na tela e abrir o Prompt de Comando)
![Sem título3](https://user-images.githubusercontent.com/55554722/147969889-1800f743-1bb4-4e58-806d-b0f1561407a8.png)

Na CMD você vai usar o comando cd e o link pra chegar dentro da pasta. Pra conseguir o link, você entra na pasta e clica na barra de caminho.
![Sem título](https://user-images.githubusercontent.com/55554722/147969929-7fb20a9f-8716-49aa-b74e-5895b3749284.png)

Depois disso você vai escrever no prompt de comando "cd link" (tudo sem aspas). Outra alternativa é você usar o cd pasta por pasta até chegar no lugar certo.
![4](https://user-images.githubusercontent.com/55554722/147969947-196fe4c9-b6e8-4e86-9989-9035c6c28e33.png)

Quando chegar dentro da pasta, você vai usar o comando "npm install" e esperar terminar. Depois disso, você usa o comando "npm start" e você vai poder acessar indo em "localhost:2200" no navegador.

**Comment by KarlaMcgees** [comment]
Depois de digitar o comando npm start, como faço para baixar as histórias?
