### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by Raid4152** [Feuerhamster/wattpad-downloader#23]
Hola, he seguido las intrsuciones pero realmente no me sale. No teneis una guia más especifica o un video? O de ser posible, no podrian ayudarme a instarlarlo o hacerlo funcionar ya sea en mi pc o un hosting que tengo?  

Olá, segui as instruções mas não funciona realmente. Tem um guia mais específico ou um vídeo? Ou, se possível, não poderia ajudar-me a instalá-lo ou fazê-lo funcionar no meu PC ou num alojamento que eu tenho?

Hi, I've followed the instructions but it doesn't really work. Don't you have a more specific guide or a video? Or if possible, couldn't you help me to install it or make it work either on my pc or a hosting I have?

**Comment by KarlaMcgees** [comment]
https://github.com/Feuerhamster/wattpad-downloader/issues/22#issuecomment-1004303325
