### ISSUE TITLE
process.env

### ISSUE THREAD

**Issue by Alinesete** [Feuerhamster/wattpad-downloader#26]
Hi, here the process.env file is not changing the download limit :/
![image](https://user-images.githubusercontent.com/55554722/151171846-cbff48f9-ecc2-4040-981f-0e46669d8ad0.png)
![image](https://user-images.githubusercontent.com/55554722/151171914-59072128-9c5f-4914-b367-b14148a55f78.png)
![image](https://user-images.githubusercontent.com/55554722/151171950-eb1e17fc-600e-40cd-94b6-a8771723778f.png)

**Comment by Feuerhamster** [comment]
Please only name the file `.env`
