### ISSUE TITLE
powershell for vc

### ISSUE THREAD

**Issue by hollandhr** [Feuerhamster/wattpad-downloader#29]
hello, can i do it in powershell without node.js? after installing node.js i got a message i need to do it with powershell, then from powershell i got a message saying node.js is a problem and after un installing node.js powershell said they dont recognize "npm" and the code.

**Comment by Feuerhamster** [comment]
Node.js is a requirement because it's the runtime for the entire project.
Sounds more like a problem with the installation of Node.js on your machine and not a problem with our software.
