### ISSUE TITLE
Public Instance

### ISSUE THREAD

**Issue by MaximilianGT500** [Feuerhamster/wattpad-downloader#34]
Hello, 
I have been hosting the domain https://Wattpad.CC with your source for a long time.
I would be happy if you would use my public instance for your reference, for an demo.

**Comment by Feuerhamster** [comment]
Thank you for hosting and participating in this project!

> I would be happy if you would use my public instance for your reference, for an demo.
Would you like to elaborate on what you mean by that? for example, do you want us to link your site as a third party in our readme?

Besides that, I would like to inform you about a few security-related aspects of this project, which are, among other things, the reason for the shutdown of our own instance. I think it's fair and important to educate you on this. Is there anywhere I can message you privately?

**Comment by MaximilianGT500** [comment]
Hello, yes you can contact me on 
Discord: MaximilianGT500#0001
E-Mail: max@max.srl
Matrix: @maximiliangt500:matrix.org
Threema: https://threema.id/K2FJTSBR
