### ISSUE TITLE
Images midchapter

### ISSUE THREAD

**Issue by Alinesete** [Feuerhamster/wattpad-downloader#4]
Hi, tysm for the amazing work!
When there is a image in the chapter and you save it as a ePub, it returns an error and only print the chapter until the image :/
![Sem títulogit](https://user-images.githubusercontent.com/55554722/126076032-c08e8dfd-0247-4e69-848c-e677d3b34d2a.png)

**Comment by Feuerhamster** [comment]
Thank you for the report!
Which book exactly did you convert?
A link or the book ID would be useful.

**Comment by Alinesete** [comment]
It was this one
https://www.wattpad.com/story/157056528-panorama-miraculous-ladybug

**Comment by Feuerhamster** [comment]
We've deployed a new version where all EPUB errors should be fixed.
