### ISSUE TITLE
[ FEATURE REQUEST ] - List & Profile Download Support #5

### ISSUE THREAD

**Issue by longwangdev** [Feuerhamster/wattpad-downloader#44]
Many Wattpad authors accidentally delete their stories quite often. Your wp-downloader is incredibly helpful in such cases!

However, I believe it would be even more useful if it supported downloading lists and profiles as well.

[This repository](https://github.com/TheOnlyWayUp/WattpadDownloader) includes support for downloading lists in [this branch](https://github.com/TheOnlyWayUp/WattpadDownloader/tree/feature/%2319-list-downloads), but I find your downloader’s UI and HTML downloads much more user-friendly and practical.

(Additionally, need to run in Docker [this repo](https://github.com/TheOnlyWayUp/WattpadDownloader) in order to download lists, as API is written in python, which can be inconvenient, for non-developers.)

Please consider.

**Comment by Feuerhamster** [comment]
Feel free to implement it yourself

**Comment by sipsuru** [comment]
Sure, I'll see what I can do.
